builders:
  normal_builder:
    import: 'package:build_runner_test/normal.dart'
    builder_factories: [ 'normalBuilder' ]
    build_extensions: { '$lib$': [ 'sample.txt' ] }
    auto_apply: root_package
    build_to: cache
    applies_builders: [ ":post_builder" ]

post_process_builders:
  post_builder:
    import: 'package:build_runner_test/post.dart'
    builder_factory: 'postBuilder'
    build_to: source
    input_extensions: [ 'intermediate.txt' ]
